require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics:
  Enabled: false
