version: '3.3'

services:
  web:
    build:
      args:
        DEV_BUILD: 'true'
    env_file: .env
    external_links:
      - ${PROXY_CONTAINER:-dinghy_http_proxy}:canvas.docker
    volumes:
      - .:/usr/src/app
      - tmp:/usr/src/app/tmp

  work:
    build:
      args:
        DEV_BUILD: 'true'
    env_file: .env
    external_links:
      - ${PROXY_CONTAINER:-dinghy_http_proxy}:canvas.docker
    volumes:
      - .:/usr/src/app
      - tmp:/usr/src/app/tmp

volumes:
  tmp:
