version: '3.3'

services:
  web:
    volumes:
      - .:/usr/src/app
      - tmp:/usr/src/app/tmp
    env_file: .env
    external_links:
      - ${PROXY_CONTAINER:-dinghy_http_proxy}:canvas.docker

  work:
    volumes:
      - .:/usr/src/app
      - tmp:/usr/src/app/tmp
    env_file: .env
    external_links:
      - ${PROXY_CONTAINER:-dinghy_http_proxy}:canvas.docker

volumes:
  tmp:
