---
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE", 5) %>
  timeout: 5000
  username: <%= ENV.fetch("DATABASE_USERNAME", "rollcall") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_ADDRESS"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *defaults
  database: <%= ENV.fetch("DATABASE_NAME", "instructure-rollcall_development") %>

test: &test
  <<: *defaults
  database: <%= ENV.fetch("DATABASE_NAME", "instructure-rollcall_test") %>

cucumber:
  <<: *test

production:
  <<: *defaults
  database: <%= ENV.fetch("DATABASE_NAME", "instructure-rollcall_production") %>
