production:
  adapter: postgresql
  encoding: unicode
  # url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE", 5) %>
  timeout: 5000
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_ADDRESS"] %>
  port: <%= ENV["DATABASE_PORT"] %>

